# Generated by Django 5.0.4 on 2024-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_my_budget', '0002_alter_account_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BRL', 'Reais (BRL)'), ('USD', 'US Dollar (USD)')], default='BRL', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
